[[redirects]]
  from = "/api/*"
  to = "https://signaltracker.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/Home/*"
  to = "https://signaltracker.onrender.com/Home/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ExcelUpload/*"
  to = "https://signaltracker.onrender.com/ExcelUpload/:splat"
  status = 200
  force = true